name: Generate Pacman Animation

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate pacman-contribution-graph (dark)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: aayushi-singhhh
          output_path: pacman-contribution-graph-dark.svg

      - name: Generate pacman-contribution-graph (light)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: aayushi-singhhh
          output_path: pacman-contribution-graph.svg
          theme: github-light

      - name: Commit and push graphs to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pacman-contribution-graph-dark.svg pacman-contribution-graph.svg
          git commit -m "Update Pacman contribution graphs [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
